server:
  port: 7007
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://server1:7000/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
zuul:
  routes:
    e-p:
      path: /e-p/**
      serviceId: eureka-provider1
    e-c:
      path: /e-c/**
      serviceId: eureka-consumer1
yxwfilter:
  ip:
    whitelist: 127.0.0.1,192.168.137.1
    whitelistenabled: true         #是否启用白名单